### ISSUE TITLE
七牛图片问题

### ISSUE THREAD

**Issue by xinz0526** [helei112g/laravel-ueditor#1]
你好，首先感谢你改进了stevenyangecho/laravel-u-editor的包，之前用该作者的包上传图片时总是提示“请求后台配置项http错误，上传功能将不能正常使用！”。
另外请教下，我在用你的ueditor时上传图片至七牛成功，但是编辑框显示不出来，然而在使用本地保存图片是编辑框则可以显示已保存的图片。求教

**Comment by xinz0526** [comment]
不好意思，原来是域名没有设置

**Comment by helei112g** [comment]
嗯，多多交流
