### ISSUE TITLE
输入数据保存问题

### ISSUE THREAD

**Issue by xinz0526** [helei112g/laravel-ueditor#2]
你好，我在ueditor输入内容后提交表单失败，后退之后无法显示原来的编辑内容，加上Input::old()也没用。我现在只知道可以从草稿箱加载回最后保存的内容。但是我希望是浏览器后退时就能显示原本的编辑内容，请问有解决方案吗？谢谢

**Comment by helei112g** [comment]
这部分内容，应该可以通过UEditor的配置文件实现，你可以查下它的配置信息。

**Comment by xinz0526** [comment]
好的，谢谢。我先看下配置信息，之前百度的时候主要不知道搜索什么关键字

**Comment by helei112g** [comment]
> 好的，谢谢。我先看下配置信息，之前百度的时候主要不知道搜索什么关键字

嗯，这个功能我也没有做过，但是我想，逻辑上应该是回退的时候，你把之前的内容放入的富文本的初始化中应该就可以完成。

**Comment by xinz0526** [comment]
我也是这么想的，我在初始化时加载一下草稿箱，但是没用。我继续找找，谢谢。
